cmake_minimum_required(VERSION 3.10...4.0)

project(TestGpuUnifiedMemory)
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/CMake)

set(CMAKE_CXX_STANDARD 17)

option(SUPPORT_ONEAPI "Build with oneAPI SYCL support." ON)

file(GLOB_RECURSE SOURCES src/*.cpp src/*.c src/*.hpp src/*.h)
list(REMOVE_ITEM SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/src/TestSycl.cpp)
include_directories(src)

if(MSVC)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -W3 /EHsc /Zc:__cplusplus")
elseif(CMAKE_COMPILER_IS_GNUCXX)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
endif()

if (NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src")
    message(FATAL_ERROR "Error: Submodules are not cloned. Please call \"git submodule update --init --recursive\".")
endif()

if (NOT (MSYS OR MINGW OR (${CMAKE_GENERATOR} STREQUAL "MinGW Makefiles") OR (${CMAKE_GENERATOR} STREQUAL "MSYS Makefiles")))
    find_package(CUDAToolkit QUIET)
    if(${CUDAToolkit_FOUND})
        if(${CUDAToolkit_VERSION} VERSION_LESS "11.5")
            MESSAGE(FATAL_ERROR "CUDA version >= 11.5 is required, but ${CUDAToolkit_VERSION} was found.")
        endif()
    endif()
endif()
if(${CUDAToolkit_FOUND})
    MESSAGE(STATUS "Found CUDA toolkit ${CUDAToolkit_VERSION}")
endif()

if (NOT (MSYS OR MINGW OR (${CMAKE_GENERATOR} STREQUAL "MinGW Makefiles") OR (${CMAKE_GENERATOR} STREQUAL "MSYS Makefiles")))
    find_package(hip QUIET)
endif()
if(${hip_FOUND})
    MESSAGE(STATUS "Found HIP SDK ${hip_VERSION}")
endif()

if (NOT (MSYS OR MINGW OR (${CMAKE_GENERATOR} STREQUAL "MinGW Makefiles") OR (${CMAKE_GENERATOR} STREQUAL "MSYS Makefiles")) AND ${SUPPORT_ONEAPI})
    find_package(SYCL QUIET)
    if(SYCL_FOUND)
        set(USE_ONEAPI ON)
    endif()
endif()

list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Convert.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/StringUtils.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Format.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Env.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Dialog.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Timer.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/AppSettings.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Json/SimpleJson.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/File/Execute.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/File/FileLoader.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/File/Logfile.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/File/FileUtils.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Events/EventManager.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Events/Stream/BinaryStream.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Events/Stream/StringStream.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/Widgets/NumberFormatting.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/GLSL/PreprocessorGlsl.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/libs/volk/volk.c")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/libs/SPIRV-Reflect/spirv_reflect.c")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/VmaImpl.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/Memory.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/Instance.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/Status.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/Device.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/SyncObjects.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Buffers/Buffer.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Buffers/Framebuffer.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Image/Image.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Shader/Shader.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Shader/ShaderManager.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/CommandBuffer.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/Pipeline.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/ComputePipeline.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/GraphicsPipeline.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/RayTracingPipeline.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/Data.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/Helpers.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/Renderer.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/Passes/Pass.cpp")

# Interop code.
if(${CUDAToolkit_FOUND})
    list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Utils/InteropCuda.cpp")
    list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/InteropCuda.cpp")
endif()
if(${hip_FOUND})
    list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Utils/InteropHIP.cpp")
    list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/InteropHIP.cpp")
endif()

add_library(sgl STATIC ${SOURCES_SGL})
target_include_directories(sgl PUBLIC third_party)
target_include_directories(sgl PUBLIC third_party/sgl/src)
target_include_directories(sgl PUBLIC third_party/sgl/src/Graphics/Vulkan/libs)
target_include_directories(sgl PUBLIC third_party/sgl/src/Graphics/Vulkan/libs/Vulkan-Headers)
target_compile_definitions(sgl PUBLIC DLL_OBJECT=)
target_compile_definitions(sgl PUBLIC SUPPORT_VULKAN)
target_compile_definitions(sgl PUBLIC SUPPORT_GLSLANG_BACKEND)
target_compile_definitions(sgl PUBLIC DISABLE_IMGUI)
target_compile_definitions(sgl PUBLIC DISABLE_VULKAN_SWAPCHAIN_SUPPORT)
target_compile_definitions(sgl PUBLIC DISABLE_DEVICE_SELECTION_SUPPORT)
target_compile_definitions(sgl PUBLIC DISABLE_SCENE_GRAPH_SOURCES)
if (WIN32)
    target_compile_definitions(sgl PUBLIC DISABLE_SINGLETON_BOOST_INTERPROCESS)
endif()
if(${CUDAToolkit_FOUND})
    target_compile_definitions(sgl PUBLIC SUPPORT_CUDA_INTEROP)
    target_include_directories(sgl PUBLIC ${CUDAToolkit_INCLUDE_DIRS})
endif()
if(${hip_FOUND})
    target_compile_definitions(sgl PUBLIC SUPPORT_HIP_INTEROP)
    target_include_directories(sgl PUBLIC ${hip_INCLUDE_DIRS})
endif()

if (WIN32)
    set(GLSLANG_SYS_NAME "Windows")
else()
    set(GLSLANG_SYS_NAME "Unix")
endif()
file(GLOB_RECURSE SOURCES_GLSLANG
        third_party/glslang/SPIRV/*.cpp
        third_party/glslang/glslang/CInterface/*.cpp
        third_party/glslang/glslang/GenericCodeGen/*.cpp
        third_party/glslang/glslang/MachineIndependent/*.cpp
        third_party/glslang/glslang/ResourceLimits/*.cpp)
file(GLOB_RECURSE SOURCES_GLSLANG
        third_party/glslang/SPIRV/*.cpp
        third_party/glslang/glslang/CInterface/*.cpp
        third_party/glslang/glslang/GenericCodeGen/*.cpp
        third_party/glslang/glslang/MachineIndependent/*.cpp
        third_party/glslang/glslang/ResourceLimits/*.cpp
        third_party/glslang/glslang/OSDependent/${GLSLANG_SYS_NAME}/*.cpp)
add_library(glslang STATIC ${SOURCES_GLSLANG})
target_compile_definitions(glslang PRIVATE ENABLE_SPIRV)
target_include_directories(glslang PUBLIC third_party/glslang)
target_include_directories(glslang PUBLIC third_party/custom)

target_link_libraries(sgl PRIVATE glslang)
add_executable(TestGpuUnifiedMemory ${SOURCES} ${CUDA_SOURCES})
target_link_libraries(TestGpuUnifiedMemory PRIVATE sgl)

if (NOT MSVC)
    if (NOT CMAKE_BUILD_TYPE STREQUAL "Debug")
        target_compile_definitions(TestGpuUnifiedMemory PRIVATE NDEBUG)
    endif()
endif()

if(MSVC)
    set_target_properties(TestGpuUnifiedMemory PROPERTIES LINK_FLAGS_DEBUG "/SUBSYSTEM:CONSOLE")
    set_target_properties(TestGpuUnifiedMemory PROPERTIES COMPILE_DEFINITIONS_DEBUG "_CONSOLE")
    set_target_properties(TestGpuUnifiedMemory PROPERTIES LINK_FLAGS_RELWITHDEBINFO "/SUBSYSTEM:CONSOLE")
    set_target_properties(TestGpuUnifiedMemory PROPERTIES COMPILE_DEFINITIONS_RELWITHDEBINFO "_CONSOLE")
    set_target_properties(TestGpuUnifiedMemory PROPERTIES LINK_FLAGS_RELEASE "/SUBSYSTEM:CONSOLE")
    set_target_properties(TestGpuUnifiedMemory PROPERTIES LINK_FLAGS_MINSIZEREL "/SUBSYSTEM:CONSOLE")
endif()

if(${CUDAToolkit_FOUND})
    enable_language(CUDA)
    set_target_properties(TestGpuUnifiedMemory PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
    file(GLOB_RECURSE CUDA_SOURCES src/*.cu)
    add_library(CudaKernels SHARED ${CUDA_SOURCES})
    if (WIN32)
        set(DLLIMPORT "__declspec(dllimport)")
        set(DLLEXPORT "__declspec(dllexport)")
        target_compile_definitions(CudaKernels INTERFACE DLL_OBJECT_CUDA=${DLLIMPORT})
        target_compile_definitions(CudaKernels PRIVATE DLL_OBJECT_CUDA=${DLLEXPORT})
    else()
        target_compile_definitions(CudaKernels PUBLIC DLL_OBJECT_CUDA=)
    endif()
    target_compile_definitions(CudaKernels PRIVATE DLL_OBJECT=)
    target_compile_options(CudaKernels PRIVATE "-Wno-deprecated-gpu-targets")
    target_include_directories(CudaKernels PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
    target_include_directories(CudaKernels PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src")
    target_link_libraries(TestGpuUnifiedMemory PRIVATE CudaKernels)
    target_compile_definitions(TestGpuUnifiedMemory PRIVATE SUPPORT_CUDA)
endif()

if(${hip_FOUND})
    enable_language(HIP)
    set_target_properties(TestGpuUnifiedMemory PROPERTIES HIP_SEPARABLE_COMPILATION ON)
    file(GLOB_RECURSE HIP_SOURCES src/*.hip)
    add_library(HipKernels SHARED ${HIP_SOURCES})
    if (WIN32)
        set(DLLIMPORT "__declspec(dllimport)")
        set(DLLEXPORT "__declspec(dllexport)")
        target_compile_definitions(HipKernels INTERFACE DLL_OBJECT_HIP=${DLLIMPORT})
        target_compile_definitions(HipKernels PRIVATE DLL_OBJECT_HIP=${DLLEXPORT})
    else()
        target_compile_definitions(HipKernels PUBLIC DLL_OBJECT_HIP=)
    endif()
    target_compile_definitions(HipKernels PRIVATE DLL_OBJECT=)
    target_compile_options(HipKernels PRIVATE "-Wno-deprecated-gpu-targets")
    target_include_directories(HipKernels PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
    target_include_directories(HipKernels PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src")
    target_link_libraries(TestGpuUnifiedMemory PRIVATE HipKernels)
    target_compile_definitions(TestGpuUnifiedMemory PRIVATE SUPPORT_HIP)
    target_link_libraries(TestGpuUnifiedMemory PRIVATE hip::host)
endif()

if (USE_ONEAPI)
    set(TEST_ONEAPI_DEVICE_SOURCES "src/TestSycl.cpp")
    list(APPEND ONEAPI_COMPILER_FLAGS "-I" "${CMAKE_CURRENT_SOURCE_DIR}/src")
    if (WIN32)
        set(DLLIMPORT "__declspec(dllimport)")
        set(DLLEXPORT "__declspec(dllexport)")
        target_compile_definitions(TestGpuUnifiedMemory PRIVATE DLL_OBJECT_SYCL=${DLLIMPORT})
        list(APPEND ONEAPI_COMPILER_FLAGS "-D" "DLL_OBJECT_SYCL=${DLLEXPORT}")
    else()
        target_compile_definitions(TestGpuUnifiedMemory PRIVATE DLL_OBJECT_SYCL=)
        list(APPEND ONEAPI_COMPILER_FLAGS "-D" "DLL_OBJECT_SYCL=")
    endif()

    target_link_sycl_host(TestGpuUnifiedMemory)
    compile_sycl_kernels(TestGpuUnifiedMemory "${TEST_ONEAPI_DEVICE_SOURCES}" "${ONEAPI_COMPILER_FLAGS}" "${ONEAPI_LINKER_FLAGS}")
    target_compile_definitions(TestGpuUnifiedMemory PUBLIC SUPPORT_SYCL)
    copy_sycl_libs_to_target(TestGpuUnifiedMemory)
endif()
